version: '3'
services:  
  nginx:
    depends_on:
      - pwa-app
      - api
      - backend-server
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - 3050:80   
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./api:/app  
  backend-server:
    build:
      context: ./backend-server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./backend-server:/app
  pwa-app:
    build:
      context: ./pwa-app
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./pwa-app:/app    

